language: r
os:
  - linux
  - osx
sudo: false
cache: packages
r_github_packages:
  - phylotastic/rphylotastic
  - fmichonneau/phyloch
script:
  - R CMD build .
  - travis_wait 66 R CMD check datelife*tar.gz
warnings_are_errors: false
# r_check_args: --as-cran
env:
  global:
  - R_CHECK_FORCE_SUGGESTS=false
# r_check-args:
#   - force_suggests: false
r_packages:
  - covr
install:
# - ./travis-tool.sh install_deps
#  - cp ../travis-tool.sh ./travis-tool.sh
#  - ./travis-tool.sh install_github phylotastic/rphylotastic
after_success:
  - Rscript -e 'library(covr); codecov()'
# before_script:
#   - sudo chmod +x /usr/local/bin/PATHd8.c  # to access this directory. Does not seem to work.
before_install:
  #  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  #  - chmod 755 ./travis-tool.sh
  #  - ./travis-tool.sh bootstrap
 #   - cp ../travis-tool.sh ./travis-tool.sh
  #  - ./travis-tool.sh install_github phylotastic/rphylotastic
  # - chmod +x install-dependencies.sh  # to run this .sh
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm '/usr/local/bin/gfortran' ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask uninstall oclint ; fi # based on https://github.com/travis-ci/travis-ci/issues/8826
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  #  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --overwrite gcc          ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap brewsci/bio; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install brewsci/bio/mrbayes; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install brewsci/science/pathd8; fi

#   alternatively, on terminal:
#       git update-index --add --chmod=+x install-dependencies.sh
#       git commit -m 'Make install-dependencies.sh executable'
#       git push
# install:  # to install pathd8
#   ./install-dependencies.sh
