language: r
sudo: false
cache: packages
warnings_are_errors: true
# r_check_args: --as-cran
env:
  global:
  - R_CHECK_FORCE_SUGGESTS=false
# r_check-args:
#   - force_suggests: false

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
