language: r
cache: packages
latex: false
r_github_packages:
  - phylotastic/rphylotastic
  - fmichonneau/phyloch
r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr); codecov()'
fortran: false
env:
  - _R_CHECK_FORCE_SUGGESTS_=false
warnings_are_errors: false
matrix:
  include:
    - os: osx
      brew_packages:
        - imagemagick
        - fortran
    - dist: xenial
        apt:
          update: true
          packages:
            - fortran
            - libmagick++-dev
            - librsvg2-dev
            - libwebp-dev
            - libpoppler-cpp-dev
            - libtesseract-dev
            - libleptonica-dev
            - tesseract-ocr-eng
            - r-cran-rgdal
            - libfftw3-dev
            - cargo
